thedavidwenk/costumize

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20240529093026_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
I created a user model with the Devise gem. It's fully functional for bsic sign up and log in.
=> Created User Model

app/controllers/pages_controller.rb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Worked on Sign Up and Log In: 
* did some bootstrap for centering
* Log in should now be skipped for home, show and index page!
=> User Authentication basics done

app/views/costumes/index.html.erb, app/views/layouts/application.html.erb
Created a skeleton for the costumes-index page, added a search bar with no functionality. Also added a container to the main layout.
=> Costumes index

app/controllers/costumes_controller.rb
added authentification skip for home, index and show pages
=> added authentification skip for home, index and show pages

app/views/costumes/_search.html.erb, app/views/costumes/index.html.erb
Moved the search bar to _search.html.erb and rendered it on Costumes#index.
=> Just moved the sidebar to a partial file

app/controllers/costumes_controller.rb, app/javascript/controllers/search_controller.js, app/views/costumes/_results.html.erb, app/views/costumes/_search.html.erb, app/views/costumes/index.html.erb
Split the search bar in accordance to our brief discussion this morning. Controller has been changed so that each category is displayed - no actual functionality implemented at this stage.
=> Split search bar into sections to reflect search categories

app/controllers/costumes_controller.rb, app/models/costume.rb, app/views/costumes/_results.html.erb, app/views/costumes/new.html.erb, app/views/costumes/show.html.erb
- change model and controller to handle multiple imgs during upload
- upadated index dealing now with an array of images
- updated show page with an image carusel.
=> add multiple image upload and integrated img into show page

app/controllers/costumes_controller.rb, app/views/costumes/_search.html.erb
=> Added placeholders and "view all" option to search bar

app/views/costumes/_results.html.erb, app/views/costumes/index.html.erb
Changed size of cards to accommodate new size of images (from landscape to portrait), added margin to bottom of index page, made whole card clickable.
=> Costume cards updates

app/views/costumes/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb
* made sure password input is hidden 
* added margin and button classes 
* removed "minimum characters needed" for name and address inputs 
* added autofocus to "First Name" so the user can start right from the top
=> Fixed Signup issues

app/controllers/costumes_controller.rb, app/views/costumes/new.html.erb
* added minimum value to price input in create form
* changed redirect when creating a costume
=> fixed price input. can't go negative

app/views/bookings/new.html.erb, app/views/costumes/new.html.erb
* added back links to the booking page and the create new form
* added required attribute to the form and autofocus on the first input
=> added back links and improved 'create new' form

app/javascript/controllers/card_hover_controller.js, app/views/costumes/_results.html.erb
Added a bootstrap shadow to cards when you hover over them, using StimulusJS.
=> Added hover effect to cards

app/views/costumes/_results.html.erb
Reverts thedavidwenk/costumize#38
=> Revert "Responsive cards"

app/assets/stylesheets/components/_alert.scss, app/javascript/controllers/notification_controller.js, app/views/shared/_navbar.html.erb
* notifications are now on the bottom right and they disappear after 3 seconds
=> repositioned notifications

app/assets/stylesheets/components/_index.scss, app/controllers/costumes_controller.rb, app/controllers/users_controller.rb, app/models/costume.rb, app/views/users/index.html.erb
- added delete costume function for users own costumes 
- added association that bookings with this costumes will be deleted automatically as well
- added trashcan icon on costume card
=> Add Delete method for user costumes

app/models/costume.rb, app/views/costumes/show.html.erb, app/views/shared/_modal.html.erb
* the modal is now showing a confirmation and links to the overview page
* once the costume form is done, it can be attached to the form submit button
Fixed:
* I also removed the title uniqueness from the costume model
* the "rent" button on the costume page is now at the bottom
=> modal is ready for form submit

app/assets/stylesheets/components/_index.scss, app/controllers/costumes_controller.rb, app/views/costumes/_results.html.erb, app/views/costumes/edit.html.erb, app/views/users/index.html.erb, config/routes.rb
- Add "edit" icon to costume card on my costumes tab
- Add ability to add new photos and delete them in edit window
- Add ability to edit costume data
=> Edit costume

app/controllers/costumes_controller.rb
Just cleaned the code up a bit. We'll see if it will change after I finish the Search lecture.
=> Search updates

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/typed_controller.js, app/views/costumes/_results.html.erb, app/views/costumes/home.html.erb, app/views/costumes/index.html.erb
- Remove borders
- added a carusel if more than two images
- font adjustments
=> Card design on index page

app/views/shared/_navbar.html.erb
Struggling to center the links in the navigation - I thought it had worked before, apparently not. It seems better now.
=> Centered links

app/controllers/bookings_controller.rb
The booking is completed only if the user has input valid dates. Otherwise, a pop up alert message appears saying "Please confirm your rental dates"
=> allows booking only if date is confirmed

app/controllers/bookings_controller.rb
....somehow these changes have been lost from a previous commit. 
Changes:
- when the user tries to book without entering dates there appears an error message
=> if no dates are present error message appear when booking

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_search.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/shared/_footer.html.erb, app/views/shared/_front_search.html.erb, app/views/users/index.html.erb
- Background color light purple
- search bar white fields
- footer border top and white to increase contract
=> change background color and adjusted search bar color and footer to it

app/assets/stylesheets/components/_front_search.scss, app/views/shared/_navbar.html.erb
=> Fixed search bar border and background for the user links on the navbar

app/assets/stylesheets/components/_index.scss, app/views/costumes/new.html.erb, app/views/shared/_modal.html.erb
* modal is updated
* create form has a little note saying "max. 4"
=> Finishing touches

app/assets/stylesheets/components/_booking_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_show_column.scss, app/assets/stylesheets/components/_small_pictures.scss, app/javascript/controllers/image_switcher_controller.js, app/views/costumes/show.html.erb, app/views/shared/_booking_form.html.erb
Same changes @clarroquia made, but without the user/index page
=> Carmen's changes to show page

app/views/costumes/show.html.erb
@thedavidwenk Try Marks code first. We found issues with the maximum size and width. So in this branch we fixed height and width for the whole costume container, so it always stays the same. 
**download this to your computer and test it locally**
=> Marks code fix

app/views/costumes/show.html.erb
Give it a test but it should be sorted
=> fixed picture height
